<?php

use Drupal\form_builder\FormCenter\Manager;
use Drupal\form_builder\FormEntity;

require_once dirname(__FILE__) . '/form_builder.hooks.php';

function form_builder_form_alter($form, $form_state, $form_id)
{

}

function form_builder_form_article_node_form_alter($form, $form_state)
{
    if (!empty($_GET['debug'])) {
        dsm($form_id);
        dsm($form['body']);
    }
}

/**
 * Factory access to form-center's manger.
 *
 * @staticvar Manager $manager
 * @return Manager
 */
function form_builder_manager()
{
    static $manager = null;

    if (null === $manager) {
        $manager = new Manager();
    }

    return $manager;
}

/**
 * Wrapper for entity_access().
 *
 * @return boolean
 */
function form_builder_entity_access()
{
    if (user_access('administer forms')) {
        return true;
    }
    return call_user_func_array('entity_access', func_get_args());
}

/**
 * Wrapper for entity_load_single.
 *
 * @param int $fid
 * @return FormEntity
 */
function form_builder_load($fid)
{
    return entity_load_single('form_builder_form', $fid);
}
